#!/bin/bash

# qsub -W group_list=cu_10158 -A cu_10158 -l nodes=2:ppn=20,mem=256gb,walltime=4:00:00 runTrust4_MM15_AUTO_A.sh

module load tools
module load trust4/1.0.12

cd $PBS_O_WORKDIR

# File paths
bam=/possorted_genome_bam.bam
hg38_bcrtcr=/trust4/genome/hg38_bcrtcr.fa
human_IMGT_C=trust4/genome/human_IMGT+C.fa

# Run the Trust4 tool
run-trust4 -t 8 -b $bam -f $hg38_bcrtcr --ref $human_IMGT_C --barcode CB
